<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-479UF7K" failures="1" tests="10" name="Test1_parallel" time="13.729" errors="0" timestamp="2025-08-03T23:37:09 IST">
  <testcase classname="tests.DdUserTest" name="testPostUser" time="4.223"/>
  <testcase classname="tests.userTest2" name="testPostUser" time="5.105">
    <failure type="java.lang.AssertionError" message="expected [1020] but found [1010]">
      <![CDATA[java.lang.AssertionError: expected [1020] but found [1010]
at tests.userTest2.testPostUser(userTest2.java:47)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="tests.DdUserTest" name="testPostUser" time="1.654"/>
  <testcase classname="tests.userTest2" name="testGetUserByName" time="1.623"/>
  <testcase classname="tests.DdUserTest" name="testPostUser" time="1.607"/>
  <testcase classname="tests.DdUserTest" name="testDeleteUserByName" time="1.556"/>
  <testcase classname="tests.userTest2" name="testUpdateUserByName" time="3.227"/>
  <testcase classname="tests.DdUserTest" name="testDeleteUserByName" time="1.616"/>
  <testcase classname="tests.userTest2" name="testDeleteUserByName" time="1.599"/>
  <testcase classname="tests.DdUserTest" name="testDeleteUserByName" time="1.675"/>
</testsuite> <!-- Test1_parallel -->
